inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - '.rubocop_todo.yml'

# Extensions
plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

# Enforce no trailing whitespace (removed from todo file)
Layout/TrailingWhitespace:
  Enabled: true

# Allow feature descriptions in system specs instead of requiring class/module names
RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
