inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - '.rubocop_todo.yml'

# Extensions
plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

# Enforce no trailing whitespace (removed from todo file)
Layout/TrailingWhitespace:
  Enabled: true

# Enforce single quotes for string literals
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Allow feature/behavior descriptions instead of requiring class/module names
RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/requests/**/*'
    - 'spec/lib/tasks/**/*'
    - 'spec/models/*_cascade_delete_spec.rb'

# Allow negation matchers after visit in authorization specs
# These specs specifically test absence of UI elements for unauthorized users
Capybara/NegationMatcherAfterVisit:
  Exclude:
    - 'spec/features/authentication_spec.rb'
    - 'spec/system/user_role_authorization_spec.rb'
    - 'spec/system/week_navigation_spec.rb'
